config/routes.rb
Rails.application.routes.draw do
  root 'memos#index'
  resources :memos, only: [:index, :create, :update, :destroy]
  get "/memos/completed" => "memos#index_completed"
  get "/memos/sort/:sort" => "memos#index"
  post "/complete" => "memos#completedToggle"

end

app/models/memo.rb
class Memo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  def index
    sort = case params[:sort]
           when "due"  then "due"
           when "priority"   then "priority DESC"
           else
            "id"
           end
           
    @memos = Memo.where(completed: false).order(sort)
    @notifications = []
    for m in @memos.where.not(due: nil)
      if (m.due - Time.now) < 0
        @notifications.push(m);
      end
    end
  end
  
  def index_completed
    @memos = Memo.where(completed: true)
  end

  def create
    @memo = Memo.new(title: params[:memo_title], content: params[:memo_content])
    
    # due check
    if params[:due_checked] == "true"
      if !params[:memo_due_date].blank?
        @memo.due = Time.parse((params[:memo_due_date]+" "+params[:memo_due_time]))
      end
    end
    
    # priroty check
    if !params[:memo_priority].blank?
      @memo.priority = params[:memo_priority]
    end
    
    if @memo.save
      redirect_to memos_path
    else
      redirect_to :back
    end
  end

  def update
    @memo = Memo.find(params[:id])
    @memo.title = params[:memo_title]
    @memo.content = params[:memo_content]
    
    # due check
    if params[:due_checked] == "true"
      if !params[:memo_due_date].blank?
        @memo.due = Time.parse((params[:memo_due_date]+" "+params[:memo_due_time]))
      end
    else
      @memo.due = nil
    end
    
    # priroty check
    if !params[:memo_priority].blank?
      @memo.priority = params[:memo_priority]
    end
    
    if @memo.save
      redirect_to memos_path
    else
      redirect_to :back
    end
  end

  def destroy
    @memo = Memo.find(params[:id])
    @memo.destroy
    redirect_to memos_path
  end
  
  def completedToggle
    memo = Memo.find(params[:id])

    if memo.completed == false
      memo.completed = true
    else
      memo.completed = false
    end
    
    memo.save
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/views/layouts/_navbar.html.erb
<nav class="main-navbar navbar navbar-expand-lg navbar-color">
  <a class="navbar-brand" href="/"><%= image_tag("logo.png", class: "navbar-logo")%></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <%= image_tag("menu-button.png", class: "navbar-bell")%>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <%= image_tag("dot.png", class: "nav-active-dot")%>
      <li class="nav-item active">
        <a class="nav-link" href="/memos">ToDo 리스트</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/memos/completed">완료 리스트</a>
      </li>
    </ul>
    <div class="my-2 my-lg-0" data-toggle="modal" data-target="#notifiactionModal">
      <button class="remove_buttonshape navbar-bell-button" data-toggle="tooltip" data-placement="bottom" title="알림">
        <% if !@notifications.blank? %>
          <span class="notifications-counter"><%= @notifications.count %></span>
        <% end %>
        <%= image_tag("bell.png", class: "navbar-bell")%>
      </button>
    </div>
  </div>
</nav>

<!-- Modal -->
<div class="modal fade" id="notifiactionModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">마감 시간 초과 알림</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <% if @notifications.blank? %>
          마감 시간이 초과된 ToDo가 없습니다.
        <% else %>
          <% @notifications.each do |notification| %>
            <%
              if !notification.due.blank?
                  dueDate = notification.due
                  year = dueDate.year.to_s
                  month = dueDate.month.to_s
                  day = dueDate.day.to_s
                  hour = dueDate.hour.to_s
                  min = dueDate.min.to_s
                  
                  dueString = year+"년 "+month+"월 "+day+"일 "+ "/ "+hour+"시 "+min+"분 마감"
              else
                  dueString = ""
              end
            %>
          	<div class="row mt-2">
          		<div class="col-sm-12">
          			<div class="card border-danger" id="alert_<%= notification.id %>">
          				<div class="card-header">
          				    <i class="fa fa-clock-o" aria-hidden="true"></i>
          				    <span id="alert_<%= notification.id %>">
          				      마감 기한이 지났습니다.
          				    </span>
          			    </div>
          				<div class="card-body">
          					<h5 class="card-title"><%= notification.title %></h5>
          					<p class="card-text">
          						<%= notification.content %>
          					</p>
          					<div>
          					    <% if notification.priority > 0 %>
              					    <% for i in 1..notification.priority  %>
                  					    <i class="fa fa-star priority-star" aria-hidden="true"></i>
              					    <% end %>
          					    <% end %>
          					    <% for i in 1..(5-notification.priority)  %>
              					    <i class="fa fa-star-o priority-star" aria-hidden="true"></i>
          					    <% end %>
          					</div>
          					<div class="d-flex justify-content-between">
            					<div><%= dueString %></div>
            					<div class="done-update-delete d-flex justify-content-between">
                					<%= link_to memo_path(notification), method: "delete", data: { confirm: '정말 삭제하시겠습니까?' } do %>
                            <i class="fa fa-trash-o" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="삭제"></i> 
                          <% end %>
        					    </div>
          					</div>
          				</div>
          			</div>
          		</div>
          	</div>
        	<% end %>
    	  <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">닫기</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar_completed.html.erb
<nav class="main-navbar navbar navbar-expand-lg navbar-color">
  <a class="navbar-brand" href="/"><%= image_tag("logo.png", class: "navbar-logo")%></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="/memos">ToDo 리스트</a>
      </li>
      <li class="nav-item active">
        <%= image_tag("dot.png", class: "nav-active-dot-completed")%>
        <a class="nav-link" href="/memos/completed">완료 리스트</a>
      </li>
    </ul>
  </div>
  <div class="memo_menu">
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToDo List - Grepp Test</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="//stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
  <link rel="stylesheet" href="//code.jquery.com/ui/1.8.18/themes/base/jquery-ui.css" />
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="//cdn.rawgit.com/fgelinas/timepicker/master/jquery.ui.timepicker.css">
  <%= favicon_link_tag asset_path('favicon.png') %>
  
	<meta name="description" content="ToDo List App"/>
	<meta name="keywords" content="TODO"/>
	<meta name="author" content="ilovegrepp.site"/>
</head>
<body onload="startSettings()">
  <% if current_page?('/memos/completed') %>
    <%= render "layouts/navbar_completed" %>
  <% else %>
    <%= render "layouts/navbar" %>
  <% end %>
  <%= yield %>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
  <script src="//code.jquery.com/ui/1.8.18/jquery-ui.min.js"></script>
  <script src='//cdn.rawgit.com/fgelinas/timepicker/master/jquery.ui.timepicker.js'></script>
</body>
</html>

app/views/memos/_index_modal_edit.html.erb
<div class="modal fade" id="editModal_<%=memo.id%>" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title" id="editModalLabel">ToDo 수정</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_tag("/memos/"+memo.id.to_s, method: "patch") do %>
      	<div class="modal-body">
      		<div class="form-group">
      			<label class="control-label required" for="new_memo_title_<%= memo.id %>">제목</label>
      			<input required="required" autocomplete="off" value="<%= memo.title %>" class="form-control" type="text" name="memo_title" id="new_memo_title_<%= memo.id %>">
      		</div>
      		<div class="form-group">
      			<label class="control-label required" for="new_memo_content_<%= memo.id %>">내용</label>
      			<textarea class="form-control" placeholder="내용을 입력해주세요." id="new_memo_content_<%= memo.id %>" rows="10" name="memo_content" id="new_memo_content_<%= memo.id %>" required><%= memo.content %></textarea>
      		</div>
      		<div class="form-group">
      			<label class="control-label" for="new_memo_priority">중요도</label>
            <div class="rating mt-2">
              <input type="radio" name="memo_priority" value="5" id="5_<%=memo.id%>"><label for="5_<%=memo.id%>"><i class="fa fa-star-o" aria-hidden="true"></i></label>
              <input type="radio" name="memo_priority" value="4" id="4_<%=memo.id%>"><label for="4_<%=memo.id%>"><i class="fa fa-star-o" aria-hidden="true"></i></label>
              <input type="radio" name="memo_priority" value="3" id="3_<%=memo.id%>"><label for="3_<%=memo.id%>"><i class="fa fa-star-o" aria-hidden="true"></i></label>
              <input type="radio" name="memo_priority" value="2" id="2_<%=memo.id%>"><label for="2_<%=memo.id%>"><i class="fa fa-star-o" aria-hidden="true"></i></label>
              <input type="radio" name="memo_priority" value="1" id="1_<%=memo.id%>"><label for="1_<%=memo.id%>"><i class="fa fa-star-o" aria-hidden="true"></i></label>
            </div>
      		</div>
      		<div class="form-group">
    		    <div class="d-flex todo_slider">
      		    <label class="control-label mr-2" for="new_memo_due">마감 기한</label>
    		    <% if memo.due.nil? %>
      		    <label class="switch" for="slider_checkbox_<%= memo.id %>">
                <input type="checkbox" id="slider_checkbox_<%= memo.id %>"/>
                <div class="slider round"></div>
              </label>
            </div>
            <input id="due_checked_<%= memo.id %>" name="due_checked" type="hidden" value="false"/>
    			  <div class="due-input-box flex-center flex-space-between tryout-start-at">
  			    	<div class="form-group">
  			    	  <div class="input-group-flex">
          			  <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
      			      <input class="form-control" type="text" name="memo_due_date" id="memo_due_date_<%= memo.id %>" readonly/>
  			    	  </div>
            	</div>
      			</div>
      			<div class="due-input-box flex-center flex-space-between tryout-start-at">
  			    	<div class="form-group">
  			    	  <div class="input-group-flex time-position">
          			  <span class="input-group-addon"><i class="fa fa-clock-o"></i></span>
      			      <input class="form-control" type="text" name="memo_due_time" id="memo_due_time_<%= memo.id %>" readonly/>
  			    	  </div>
            	</div>
      			</div>
      			<% else %>
      			  <label class="switch" for="slider_checkbox_<%= memo.id %>">
                <input type="checkbox" id="slider_checkbox_<%= memo.id %>" checked/>
                <div class="slider round"></div>
              </label>
            </div>
    			  <input id="due_checked_<%= memo.id %>" name="due_checked" type="hidden" value="true"/>
      			<div class="due-input-box-show flex-center flex-space-between tryout-start-at">
  			    	<div class="form-group">
  			    	  <div class="input-group-flex">
          			  <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
          			  <%
          			    currentDueDateTime = memo.due.to_s
          			    currentDueDate = currentDueDateTime.split(" ")[0]
          			    currentDueTime = currentDueDateTime.split(" ")[1][0,5]
          			  %>
      			      <input class="form-control" value="<%=currentDueDate%>" type="text" name="memo_due_date" id="memo_due_date_<%= memo.id %>" readonly/>
  			    	  </div>
            	</div>
      			</div>
      			<div class="due-input-box-show flex-center flex-space-between tryout-start-at">
  			    	<div class="form-group">
  			    	  <div class="input-group-flex time-position">
          			  <span class="input-group-addon"><i class="fa fa-clock-o"></i></span>
      			      <input class="form-control" type="text" value="<%=currentDueTime%>" name="memo_due_time" id="memo_due_time_<%= memo.id %>" readonly/>
  			    	  </div>
            	</div>
      			</div>
      			<% end %>
      		</div>
      	</div>
      	<span class="error-message" id="error_message_<%= memo.id %>"></span>
      	<div class="modal-footer" onClick="validationCheck('<%= memo.id %>')">
      		<button type="button" class="btn btn-default btn-cancel" data-dismiss="modal">취소</button>
      		<input type="submit" name="commit" value="수정" class="btn btn-primary" data-disable-with="등록">
      	</div>
      <% end %>
    </div>
  </div>
</div>

app/views/memos/_index_modal_new.html.erb
<div class="modal fade" id="newModal" tabindex="-1" role="dialog" aria-labelledby="newModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title" id="newModalLabel">새로운 ToDo 작성</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_tag memos_path do %>
      	<div class="modal-body">
      		<div class="form-group">
      			<label class="control-label required" for="new_memo_title">제목</label>
      			<input required="required" autocomplete="off" placeholder="제목을 입력해주세요." class="form-control" type="text" name="memo_title" id="new_memo_title">
      		</div>
      		<div class="form-group">
      			<label class="control-label required" for="new_memo_content">내용</label>
      			<textarea class="form-control" placeholder="내용을 입력해주세요." id="new_memo_content" rows="10" name="memo_content" id="new_memo_content" required></textarea>
      		</div>
      		<div class="form-group">
      			<label class="control-label" for="new_memo_priority">중요도</label>
            <div class="rating mt-2">
              <input type="radio" name="memo_priority" value="5" id="5"><label for="5"><i class="fa fa-star-o" aria-hidden="true"></i></label>
              <input type="radio" name="memo_priority" value="4" id="4"><label for="4"><i class="fa fa-star-o" aria-hidden="true"></i></label>
              <input type="radio" name="memo_priority" value="3" id="3"><label for="3"><i class="fa fa-star-o" aria-hidden="true"></i></label>
              <input type="radio" name="memo_priority" value="2" id="2"><label for="2"><i class="fa fa-star-o" aria-hidden="true"></i></label>
              <input type="radio" name="memo_priority" value="1" id="1" checked><label for="1"><i class="fa fa-star-o" aria-hidden="true"></i></label>
            </div>
      		</div>
      		<div class="form-group">
    		    <div class="d-flex todo_slider">
      		    <label class="control-label mr-2" for="new_memo_due">마감 기한</label>
      		    <label class="switch" for="slider_checkbox">
                <input type="checkbox" id="slider_checkbox" />
                <div class="slider round"></div>
              </label>
            </div>
    		    <input id="due_checked" name="due_checked" type="hidden" value="false"/>
      			<div class="due-input-box flex-center flex-space-between tryout-start-at">
  			    	<div class="form-group">
  			    	  <div class="input-group-flex">
          			  <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
      			      <input class="form-control" type="text" name="memo_due_date" id="memo_due_date" readonly/>
  			    	  </div>
            	</div>
      			</div>
      			<div class="due-input-box flex-center flex-space-between tryout-start-at">
  			    	<div class="form-group">
  			    	  <div class="input-group-flex time-position">
          			  <span class="input-group-addon"><i class="fa fa-clock-o"></i></span>
      			      <input class="form-control" type="text" name="memo_due_time" id="memo_due_time" readonly/>
  			    	  </div>
            	</div>
      			</div>
      		</div>
      	</div>
	      <span class="error-message" id="error_message"></span>
      	<div class="modal-footer" onClick="validationCheck(0)">
      		<button type="button" class="btn btn-default btn-cancel" data-dismiss="modal">취소</button>
      		<input type="submit" name="commit" value="등록" class="btn btn-primary" data-disable-with="등록">
      	</div>
      <% end %>
    </div>
  </div>
</div>

app/views/memos/_index_modal_notifiaction.html.erb
<!--notifiaction modal-->
<div class="modal fade" id="notificationModal" tabindex="-1" role="dialog" aria-labelledby="notifiactionModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title" id="notifiactionModalLabel">마감된 ToDo 목록</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      	<div class="modal-body">
      	  <% if @notifications.count != 0 %>
              <% @notifications.each do |notification| %>
                <%
                    if !notification.due.blank?
                        dueDate = notification.due
                        year = dueDate.year.to_s
                        month = dueDate.month.to_s
                        day = dueDate.day.to_s
                        hour = dueDate.hour.to_s
                        min = dueDate.min.to_s
                        
                        dueString = year+"년 "+month+"월 "+day+"일 "+ "/ "+hour+"시 "+min+"분 마감"
                    else
                        dueString = ""
                    end
                %>
            	<div class="row mt-2">
            		<div class="col-sm-12">
            			<div class="card" id="alert_<%= notification.id %>">
            				<div class="card-header">
            				    <i class="fa fa-clock-o" aria-hidden="true"></i>
            				    <span id="due_<%= notification.id %>">
                				    <script>
                				        getLeftTime("<%= notification.id %>", "<%= notification.due %>");
                				    </script>
            				    </span>
            			    </div>
            				<div class="card-body">
            					<h5 class="card-title"><%= notification.title %></h5>
            					<p class="card-text">
            						<%= notification.content %>
            					</p>
            					<div>
            					    <% if notification.priority > 0 %>
                					    <% for i in 1..notification.priority  %>
                    					    <i class="fa fa-star priority-star" aria-hidden="true"></i>
                					    <% end %>
            					    <% end %>
            					    <% for i in 1..(5-notification.priority)  %>
                					    <i class="fa fa-star-o priority-star" aria-hidden="true"></i>
            					    <% end %>
            					</div>
            					<div class="d-flex justify-content-between">
              					<div><%= dueString %></div>
              					<div class="done-update-delete d-flex justify-content-between">
                  					<%= link_to memo_path(notification), method: "delete", data: { confirm: '정말 삭제하시겠습니까?' } do %>
                              <i class="fa fa-trash-o" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="삭제"></i> 
                            <% end %>
          					    </div>
            					</div>
            				</div>
            			</div>
            		</div>
            	</div>
          	<% end %>
      	<% end %>
      	<div class="modal-footer">
      		<button type="button" class="btn btn-default btn-cancel" data-dismiss="modal">취소</button>
      		<input type="submit" name="commit" value="등록" class="btn btn-primary" data-disable-with="등록">
      	</div>
    </div>
  </div>
</div>

app/views/memos/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light d-flex justify-content-between">
    <div id="divClock" class="clock"></div>
    <div class="dropdown-notifiaction d-flex justify-content-between">
        <div class="dropdown pr-3">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                정렬
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="/memos/">등록 순</a>
                <a class="dropdown-item" href="/memos/sort/due">마감 기한 순</a>
                <a class="dropdown-item" href="/memos/sort/priority">중요도 순</a>
            </div>
        </div>
        <ul class="navbar-nav">
        	<li class="nav-item">
                <div class="memo_menu">
                  <button type="button" class="btn btn-primary btn-create" data-toggle="modal" data-target="#newModal">작성하기</button>
                </div>
                <%= render "memos/index_modal_new" %>
        	</li>
        </ul>
    </div>
</nav>
<div class="container">
    <% @memos.each do |memo| %>
        <%
            if !memo.due.blank?
                dueDate = memo.due
                year = dueDate.year.to_s
                month = dueDate.month.to_s
                day = dueDate.day.to_s
                hour = dueDate.hour.to_s
                min = dueDate.min.to_s
                
                dueString = year+"년 "+month+"월 "+day+"일 "+ "/ "+hour+"시 "+min+"분 마감"
            else
                dueString = ""
            end
        %>
    	<div class="row mt-2">
    		<div class="col-sm-12">
    			<div class="card" id="todo_<%= memo.id %>">
    				<div class="card-header">
    				    <i class="fa fa-clock-o" aria-hidden="true"></i>
    				    <span id="due_<%= memo.id %>">
        				    <script>
        				        getLeftTime("<%= memo.id %>", "<%= memo.due %>");
        				    </script>
    				    </span>
    			    </div>
    				<div class="card-body">
    					<h5 class="card-title"><%= memo.title %></h5>
    					<p class="card-text">
    						<%= memo.content %>
    					</p>
    					<div>
    					    <% if memo.priority > 0 %>
        					    <% for i in 1..memo.priority  %>
            					    <i class="fa fa-star priority-star" aria-hidden="true"></i>
        					    <% end %>
    					    <% end %>
    					    <% for i in 1..(5-memo.priority)  %>
        					    <i class="fa fa-star-o priority-star" aria-hidden="true"></i>
    					    <% end %>
    					</div>
    					<div class="d-flex justify-content-between">
        					<div><%= dueString %></div>
        					<div class="done-update-delete d-flex justify-content-between">
        					    <div class="cb" onclick="completeToggleAjax($(this))">
        					        <input type="hidden" value="<%= memo.id %>">
        					        <% if memo.completed == false %>
                					    <input type="checkbox" id="check_<%= memo.id %>"/>
            					    <% else %>
			    					    <input type="checkbox" id="check_<%= memo.id %>" checked/>
            					    <% end %>
                                    <label for="check_<%= memo.id %>" class="check-box" data-toggle="tooltip" data-placement="top" title="완료"></label>
                                </div>
                                <button class="remove_buttonshape" data-toggle="modal" data-target="#editModal_<%=memo.id%>" onclick="editSetting('<%=memo.id%>','<%=memo.priority%>')">
                                    <i class="fa fa-pencil-square-o" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="수정"></i>
            					</button>
            					<%= link_to memo_path(memo), method: "delete", data: { confirm: '정말 삭제하시겠습니까?' } do %>
                                    <i class="fa fa-trash-o" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="삭제"></i> 
                                <% end %>
    					    </div>
    					</div>
    				</div>
    			</div>
    		</div>
    	</div>
    <%= render "memos/index_modal_edit", memo: memo %>
	<% end %>
</div>

app/views/memos/index_completed.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light d-flex justify-content-between">
	<div id="divClock" class="clock"></div>
	<div id="clock"></div>
</nav>
<div class="container">
    <% @memos.each do |memo| %>
        <%
            if !memo.due.blank?
                dueDate = memo.due
                year = dueDate.year.to_s
                month = dueDate.month.to_s
                day = dueDate.day.to_s
                hour = dueDate.hour.to_s
                min = dueDate.min.to_s
                
                dueString = year+"년 "+month+"월 "+day+"일 "+ "/ "+hour+"시 "+min+"분 마감"
            else
                dueString = ""
            end
        %>
    	<div class="row mt-2">
    		<div class="col-sm-12">
    			<div class="card border-success" id="todo_<%= memo.id %>">
    				<div class="card-header">
    				    <i class="fa fa-clock-o" aria-hidden="true"></i>
    				    <span id="due_<%= memo.id %>">완료되었습니다.</span>
    			    </div>
    				<div class="card-body">
    					<h5 class="card-title"><%= memo.title %></h5>
    					<p class="card-text">
    						<%= memo.content %>
    					</p>
    					<div>
    					    <% if memo.priority > 0 %>
        					    <% for i in 1..memo.priority  %>
            					    <i class="fa fa-star priority-star" aria-hidden="true"></i>
        					    <% end %>
    					    <% end %>
    					    <% for i in 1..(5-memo.priority)  %>
        					    <i class="fa fa-star-o priority-star" aria-hidden="true"></i>
    					    <% end %>
    					</div>
    					<div class="d-flex justify-content-between">
        					<div><%= dueString %></div>
        					<div class="done-update-delete d-flex flex-row-reverse">
            					<%= link_to memo_path(memo), method: "delete", data: { confirm: '정말 삭제하시겠습니까?' } do %>
                                    <i class="fa fa-trash-o" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="삭제"></i> 
                                <% end %>
    					    </div>
    					</div>
    				</div>
    			</div>
    		</div>
    	</div>
    <%= render "memos/index_modal_edit", memo: memo %>
	<% end %>
</div>